### PR TITLE
FIX: install launch file

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
Install launch file for using like below.

```
roslaunch choreonoid_ros launch/choreonoid.launch
```

### CODE REVIEW

**Comment by ssr-yuki** [comment]
In my understanding, installation of launch files is meaningless, while it is described in [the document of catkin](http://wiki.ros.org/catkin/CMakeLists.txt#Installing_roslaunch_Files_or_Other_Resources).

According to [the official document of roslaunch](http://wiki.ros.org/roslaunch/Commandline%20Tools), the provided basic usage of roslaunch is either of

- `roslaunch <package-name> <launch-filename>`
- `roslaunch <launch-file-paths...>`

With the former syntax, roslaunch automatically finds a file with the matching name inside the specified package. Installed directories are excluded from the search, and the syntax does not accept relative paths.

This is why we had removed the launch file installation before (you can see [the commit](https://github.com/choreonoid/choreonoid_ros/commit/bb779fe1420e3960e9e7f3b5d5b68adaa8c33a39)).

Even after I apply this PR, the command `roslaunch choreonoid_ros launch/choreonoid.launch` causes the following error in my environment (Ubuntu 20.04 / ROS1 Noetic).

```
RLException: [launch/choreonoid.launch] is neither a launch file in package [choreonoid_ros] nor is [choreonoid_ros] a launch file name
The traceback for the exception was written to the log file
```

If the command works well in your environment, please tell me how to reproduce it. Thanks.

**Comment by YoheiKakiuchi** [comment]
I'm sorry for the lack of explanation.

I am talking about installing to "Install space".
Using ```catkin config --install```

In that case, we can not use files by ROS-manner that do not explicitly describe where they are to be installed.
( we may remove directories devel, log and src in catkin_ws. )

**Comment by ssr-yuki** [comment]
I understand you want to install chorenoid_ros into the *install space* with catkin command. It is Ok.

I would just like to ask you the situation the following command works well. 

```bash
roslaunch choreonoid_ros launch/choreonoid.launch
```

Could you show me an example usage or any documents on this? Thanks.

**Comment by YoheiKakiuchi** [comment]
This is a example of using choreonoid.launch

https://github.com/IRSL-tut/irsl_choreonoid_ros/blob/main/launch/sim_robot.launch#L10-L11

It is not using at command-line, but the key point is that I would not like to use absolute path.

**Comment by ssr-yuki** [comment]
Ok. Could you check if my understanding summarized as follows is correct, please?

- Installation of built package activated by `catkin config --install` enables us to use all binaries and libraries only inside a 'install' directory (e.g., `~/catkin_ws/install`). 
- The purpose of this PR is to use launch files inside the 'install' directory, as same as the binaries and libraries.
- Once after installing launch files, we can use them without any dependencies on the `src` and `devel` directories. This is why we can remove the directories, as you said.

**Comment by YoheiKakiuchi** [comment]
They are correct.

**Comment by ssr-yuki** [comment]
Good. Thank you.

**Review by ssr-yuki — APPROVED** [review]

**Pull request merged**
