### PR TITLE
add propertiy: publishJointState for on/off publishing joint_state

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
By This PR, a user can stop to publish joint_state by BodyROSItem.
This PR do not change default behavior.

joint_state can be published using joint_state_controller through ros_control.
http://wiki.ros.org/joint_state_controller

### CODE REVIEW

**Comment by ssr-yuki** [comment]
Thank you for your proposal. The added property looks good and important.

I am just wondering if you have another candidate of the name of the flag managing publishing joint states. The current name `publishJointState` starts with a verb and such a name is not suitable for a variable name; it is often used for function names.

I have no good idea now, but I think we should rename it into `publish*ing*JointState*s*`, at least.

**Comment by YoheiKakiuchi** [comment]
Following are the candidates that I think about.

- publishing_joint_state
- enable_publishing_joint_state
- enable_publish_joint_state
- enable_joint_state_publisher
- publish_joint_state

I prefer 'publish_joint_state',  because it is the shortest name.

**Comment by ssr-yuki** [comment]
How about using `joint_state_publication` / `jointStatePublication` ?

**Comment by YoheiKakiuchi** [comment]
> How about using joint_state_publication / jointStatePublication ?

I renamed to joint_state_publication / jointStatePublication.

**Review by ssr-yuki — APPROVED** [review]
Thank you very much!

**Pull request merged**
